version: '3.6'

networks:
  sendway-api-network:
    driver: bridge

services:
  sendway-api:
    image: sendway-api
    build:
      context: .
      dockerfile: ./dockerFile
    volumes:
      - .:/home/node/api
      - ./nodemon.json:/home/node/api/nodemon.json
    depends_on:
      - sendway-pg
    networks:
      - sendway-api-network
    links:
      - sendway-pg
    container_name: sendway-api
    command: yarn dev:server
    ports:
      - '3333:3333'

  sendway-pg:
    image: postgres:latest
    container_name: sendway-pg
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./pg/:/var/lib/postgresql/data
    networks:
      - sendway-api-network
