version: '3.6'

networks:
  prodbase-mail-network:
    driver: bridge

services:
  prodbase-mail:
    image: prodbase-mail
    build:
      context: .
      dockerfile: ./dockerFile
    volumes:
      - .:/home/node/api
      - ./nodemon.json:/home/node/api/nodemon.json
    depends_on:
      - prodmail-pg
      - rabbitmq
    networks:
      - prodbase-mail-network
    links:
      - prodmail-pg
      - rabbitmq
    container_name: prodbase-mail
    command: yarn dev:server
    ports:
      - '3333:3333'

  prodmail-pg:
    image: postgres:latest
    container_name: prodmail-pg
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./pg/:/var/lib/postgresql/data
    networks:
      - prodbase-mail-network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - prodbase-mail-network
